[package]
name = "handle-errors-06"
version = "0.1.0"
authors = ["Bastian Gruber <foreach@me.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3"
