[package]
name = "handle-errors-08"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tracing = { version = "0.1", features = ["log"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
reqwest-middleware = "0.2"
