[package]
name = "handle-errors-10"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tracing = { version = "0.1", features = ["log"] }
reqwest = "0.11"
reqwest-middleware = "0.2"
sqlx = { version = "0.6", features = [ "postgres" ] }
rust-argon2 = "1"
